// admin-ui/src/app/components/ai-usage/ai-usage.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AdminService } from '../../services/admin.service';
import { AIUsage, Pagination } from '../../models/admin.models';

@Component({
  selector: 'app-ai-usage',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './ai-usage.component.html',
  styleUrls: ['./ai-usage.component.css']
})
export class AiUsageComponent implements OnInit {
  usages: AIUsage[] = [];
  pagination: Pagination | null = null;
  statistics: any = null;
  loading = true;
  error: string | null = null;

  filters = {
    provider: '',
    startDate: '',
    endDate: ''
  };

  constructor(private adminService: AdminService) {}

  ngOnInit(): void {
    this.loadAIUsage();
  }

  loadAIUsage(page: number = 1): void {
    this.loading = true;
    this.error = null;

    const filterParams: any = {};
    if (this.filters.provider) filterParams.provider = this.filters.provider;
    if (this.filters.startDate) filterParams.startDate = this.filters.startDate;
    if (this.filters.endDate) filterParams.endDate = this.filters.endDate;
    
    this.adminService.getAIUsage(page, 50, filterParams).subscribe({
      next: (data) => {
        this.usages = data.usages;
        this.pagination = data.pagination;
        this.statistics = data.statistics;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load AI usage data';
        this.loading = false;
        console.error('AI usage error:', err);
      }
    });
  }

  applyFilters(): void {
    this.loadAIUsage(1);
  }

  clearFilters(): void {
    this.filters = {
      provider: '',
      startDate: '',
      endDate: ''
    };
    this.loadAIUsage(1);
  }

  goToPage(page: number): void {
    if (this.pagination && page >= 1 && page <= this.pagination.totalPages) {
      this.loadAIUsage(page);
    }
  }

  formatNumber(num: number): string {
    return num.toLocaleString();
  }

  formatPercent(num: number): string {
    return num.toFixed(2) + '%';
  }

  formatTime(ms: number): string {
    return ms.toFixed(0) + ' ms';
  }
}

<div class="ai-usage-container">
  <h1>AI API Usage Monitoring</h1>

  <!-- Filters -->
  <div class="filters">
    <div class="filter-group">
      <label>Provider:</label>
      <select [(ngModel)]="filters.provider" class="filter-input">
        <option value="">All Providers</option>
        <option value="chatgpt">ChatGPT</option>
        <option value="gemini">Gemini</option>
      </select>
    </div>
    <div class="filter-group">
      <label>Start Date:</label>
      <input type="date" [(ngModel)]="filters.startDate" class="filter-input" />
    </div>
    <div class="filter-group">
      <label>End Date:</label>
      <input type="date" [(ngModel)]="filters.endDate" class="filter-input" />
    </div>
    <div class="filter-actions">
      <button class="btn btn-primary" (click)="applyFilters()">Apply Filters</button>
      <button class="btn btn-secondary" (click)="clearFilters()">Clear</button>
    </div>
  </div>

  <!-- Statistics Summary -->
  <div *ngIf="statistics && !loading" class="statistics">
    <h2>Summary Statistics</h2>
    <div class="cards-grid">
      <div class="card">
        <h3>Total Calls</h3>
        <p class="stat-value">{{ formatNumber(statistics.totalCalls) }}</p>
        <p class="stat-detail success">✓ {{ formatNumber(statistics.successfulCalls) }}</p>
        <p class="stat-detail error">✗ {{ formatNumber(statistics.failedCalls) }}</p>
      </div>
      
      <div class="card">
        <h3>Success Rate</h3>
        <p class="stat-value">{{ formatPercent(statistics.successRate) }}</p>
      </div>

      <div class="card">
        <h3>Total Tokens</h3>
        <p class="stat-value">{{ formatNumber(statistics.totalTokens) }}</p>
        <p class="stat-detail">Prompt: {{ formatNumber(statistics.totalPromptTokens) }}</p>
        <p class="stat-detail">Response: {{ formatNumber(statistics.totalResponseTokens) }}</p>
      </div>

      <div class="card">
        <h3>Avg Response Time</h3>
        <p class="stat-value">{{ formatTime(statistics.avgResponseTime) }}</p>
      </div>
    </div>

    <!-- By Provider -->
    <div *ngIf="statistics.byProvider && statistics.byProvider.length > 0" class="provider-stats">
      <h3>By Provider</h3>
      <table class="stats-table">
        <thead>
          <tr>
            <th>Provider</th>
            <th>Calls</th>
            <th>Total Tokens</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let provider of statistics.byProvider">
            <td>{{ provider.provider }}</td>
            <td>{{ formatNumber(provider.calls) }}</td>
            <td>{{ formatNumber(provider.totalTokens) }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div *ngIf="loading" class="loading">Loading AI usage data...</div>
  <div *ngIf="error" class="error">{{ error }}</div>

  <!-- Usage Log -->
  <div *ngIf="!loading && usages.length > 0" class="usage-content">
    <h2>Usage Log</h2>
    <table class="data-table">
      <thead>
        <tr>
          <th>Timestamp</th>
          <th>User</th>
          <th>Provider</th>
          <th>Endpoint</th>
          <th>Tokens</th>
          <th>Response Time</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let usage of usages">
          <td>{{ usage.createdAt | date:'short' }}</td>
          <td>{{ usage.user?.email || 'System' }}</td>
          <td>{{ usage.provider }}</td>
          <td class="endpoint">{{ usage.endpoint }}</td>
          <td>
            <div class="token-info">
              <span class="token-total">{{ formatNumber(usage.totalTokens) }}</span>
              <small>({{ usage.promptTokens }}/{{ usage.responseTokens }})</small>
            </div>
          </td>
          <td>{{ formatTime(usage.responseTimeMs) }}</td>
          <td>
            <span [class]="usage.success ? 'badge success' : 'badge error'">
              {{ usage.success ? 'Success' : 'Failed' }}
            </span>
            <div *ngIf="!usage.success && usage.errorMessage" class="error-message">
              {{ usage.errorMessage }}
            </div>
          </td>
        </tr>
      </tbody>
    </table>

    <!-- Pagination -->
    <div *ngIf="pagination" class="pagination">
      <button 
        class="btn btn-secondary" 
        (click)="goToPage(pagination.page - 1)"
        [disabled]="pagination.page === 1"
      >
        Previous
      </button>
      <span class="page-info">
        Page {{ pagination.page }} of {{ pagination.totalPages }} 
        ({{ pagination.total }} total)
      </span>
      <button 
        class="btn btn-secondary" 
        (click)="goToPage(pagination.page + 1)"
        [disabled]="pagination.page === pagination.totalPages"
      >
        Next
      </button>
    </div>
  </div>

  <div *ngIf="!loading && usages.length === 0" class="no-data">
    No AI usage data found for the selected filters.
  </div>
</div>

// admin-ui/src/app/dashboard/ai-usage/page.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import { adminService, AIUsage } from '../../services/admin.service'
import {
  Bot,
  Filter,
  ChevronLeft,
  ChevronRight,
  Loader2,
  CheckCircle,
  XCircle,
  Clock,
  Activity,
  TrendingUp,
  Zap,
} from 'lucide-react'
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from 'recharts'
import { format, subDays } from 'date-fns'

export default function AIUsagePage() {
  const [usages, setUsages] = useState<AIUsage[]>([])
  const [statistics, setStatistics] = useState<any>(null)
  const [pagination, setPagination] = useState({
    page: 1,
    limit: 50,
    total: 0,
    totalPages: 0,
  })
  const [filters, setFilters] = useState({
    provider: '',
    startDate: format(subDays(new Date(), 30), 'yyyy-MM-dd'),
    endDate: format(new Date(), 'yyyy-MM-dd'),
  })
  const [isLoading, setIsLoading] = useState(true)
  const [showFilters, setShowFilters] = useState(false)

  const loadUsages = useCallback(async (page = 1) => {
    try {
      setIsLoading(true)
      const result = await adminService.getAIUsage({
        page,
        limit: 50,
        provider: filters.provider || undefined,
        startDate: filters.startDate || undefined,
        endDate: filters.endDate || undefined,
      })
      setUsages(result.usages)
      setPagination(result.pagination)
      setStatistics(result.statistics)
    } catch (err) {
      console.error('Failed to load AI usage:', err)
    } finally {
      setIsLoading(false)
    }
  }, [filters])

  useEffect(() => {
    loadUsages()
  }, [loadUsages])

  const handleFilterSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    loadUsages(1)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <h1 className="text-2xl font-bold text-gray-900">AI Usage</h1>
        <button
          onClick={() => setShowFilters(!showFilters)}
          className="inline-flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition"
        >
          <Filter className="w-5 h-5" />
          Bộ lọc
        </button>
      </div>

      {/* Filters */}
      {showFilters && (
        <div className="bg-white rounded-xl shadow-sm p-4">
          <form onSubmit={handleFilterSubmit} className="flex flex-wrap gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Provider
              </label>
              <select
                value={filters.provider}
                onChange={(e) =>
                  setFilters({ ...filters, provider: e.target.value })
                }
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
              >
                <option value="">Tất cả</option>
                <option value="chatgpt">ChatGPT</option>
                <option value="gemini">Gemini</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Từ ngày
              </label>
              <input
                type="date"
                value={filters.startDate}
                onChange={(e) =>
                  setFilters({ ...filters, startDate: e.target.value })
                }
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Đến ngày
              </label>
              <input
                type="date"
                value={filters.endDate}
                onChange={(e) =>
                  setFilters({ ...filters, endDate: e.target.value })
                }
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
              />
            </div>
            <div className="flex items-end">
              <button
                type="submit"
                className="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition"
              >
                Áp dụng
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Statistics Cards */}
      {statistics && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCard
            title="Tổng API calls"
            value={statistics.totalCalls}
            icon={<Activity className="w-6 h-6" />}
            color="blue"
          />
          <StatCard
            title="Thành công"
            value={statistics.successfulCalls}
            subtext={`${statistics.successRate.toFixed(1)}%`}
            icon={<CheckCircle className="w-6 h-6" />}
            color="green"
          />
          <StatCard
            title="Tổng tokens"
            value={statistics.totalTokens}
            icon={<Zap className="w-6 h-6" />}
            color="purple"
          />
          <StatCard
            title="TB response time"
            value={`${Math.round(statistics.avgResponseTime)}ms`}
            icon={<Clock className="w-6 h-6" />}
            color="orange"
            isText
          />
        </div>
      )}

      {/* Provider Stats */}
      {statistics && statistics.byProvider.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">
            Theo Provider
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {statistics.byProvider.map((provider: any) => (
              <div
                key={provider.provider}
                className="p-4 border border-gray-200 rounded-lg"
              >
                <div className="flex items-center gap-3 mb-2">
                  <div
                    className={`w-10 h-10 rounded-full flex items-center justify-center ${
                      provider.provider === 'chatgpt'
                        ? 'bg-emerald-100'
                        : 'bg-blue-100'
                    }`}
                  >
                    <Bot
                      className={`w-5 h-5 ${
                        provider.provider === 'chatgpt'
                          ? 'text-emerald-600'
                          : 'text-blue-600'
                      }`}
                    />
                  </div>
                  <h4 className="font-semibold text-gray-900 capitalize">
                    {provider.provider}
                  </h4>
                </div>
                <div className="space-y-1 text-sm">
                  <p className="flex justify-between">
                    <span className="text-gray-500">Calls:</span>
                    <span className="font-medium">{provider.calls}</span>
                  </p>
                  <p className="flex justify-between">
                    <span className="text-gray-500">Tokens:</span>
                    <span className="font-medium">
                      {provider.totalTokens.toLocaleString()}
                    </span>
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Usage Table */}
      <div className="bg-white rounded-xl shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900">Chi tiết calls</h3>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center h-64">
            <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
          </div>
        ) : usages.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-64 text-gray-500">
            <Bot className="w-12 h-12 mb-4" />
            <p>Không có dữ liệu</p>
          </div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Thời gian
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Người dùng
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Provider
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Endpoint
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Tokens
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Response
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-gray-600 uppercase">
                      Trạng thái
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {usages.map((usage) => (
                    <tr key={usage.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(usage.createdAt).toLocaleString('vi-VN')}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm">
                          <p className="text-gray-900">
                            {usage.user?.name || usage.user?.email || 'System'}
                          </p>
                          {usage.user?.email && usage.user.name && (
                            <p className="text-gray-500 text-xs">
                              {usage.user.email}
                            </p>
                          )}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span
                          className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${
                            usage.provider === 'chatgpt'
                              ? 'bg-emerald-100 text-emerald-700'
                              : 'bg-blue-100 text-blue-700'
                          }`}
                        >
                          <Bot className="w-3 h-3" />
                          {usage.provider}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {usage.endpoint}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <div className="space-y-0.5">
                          <p className="font-medium text-gray-900">
                            {usage.totalTokens.toLocaleString()}
                          </p>
                          <p className="text-xs text-gray-500">
                            {usage.promptTokens} / {usage.responseTokens}
                          </p>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {usage.responseTimeMs}ms
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {usage.success ? (
                          <span className="inline-flex items-center gap-1 px-2 py-1 bg-green-100 text-green-700 rounded-full text-xs font-medium">
                            <CheckCircle className="w-3 h-3" />
                            OK
                          </span>
                        ) : (
                          <span
                            className="inline-flex items-center gap-1 px-2 py-1 bg-red-100 text-red-700 rounded-full text-xs font-medium cursor-help"
                            title={usage.errorMessage || 'Unknown error'}
                          >
                            <XCircle className="w-3 h-3" />
                            Failed
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            <div className="flex items-center justify-between px-6 py-4 border-t border-gray-200">
              <p className="text-sm text-gray-500">
                Hiển thị {(pagination.page - 1) * pagination.limit + 1} -{' '}
                {Math.min(pagination.page * pagination.limit, pagination.total)}{' '}
                trên {pagination.total} records
              </p>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => loadUsages(pagination.page - 1)}
                  disabled={pagination.page <= 1}
                  className="p-2 rounded-lg border border-gray-300 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
                >
                  <ChevronLeft className="w-5 h-5" />
                </button>
                <span className="px-4 py-2 text-sm">
                  {pagination.page} / {pagination.totalPages}
                </span>
                <button
                  onClick={() => loadUsages(pagination.page + 1)}
                  disabled={pagination.page >= pagination.totalPages}
                  className="p-2 rounded-lg border border-gray-300 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
                >
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  )
}

interface StatCardProps {
  title: string
  value: number | string
  subtext?: string
  icon: React.ReactNode
  color: 'blue' | 'green' | 'purple' | 'orange'
  isText?: boolean
}

function StatCard({ title, value, subtext, icon, color, isText }: StatCardProps) {
  const colorClasses = {
    blue: 'bg-blue-100 text-blue-600',
    green: 'bg-green-100 text-green-600',
    purple: 'bg-purple-100 text-purple-600',
    orange: 'bg-orange-100 text-orange-600',
  }

  return (
    <div className="bg-white rounded-xl shadow-sm p-6">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm text-gray-500 mb-1">{title}</p>
          <p className="text-2xl font-bold text-gray-900">
            {isText ? value : (value as number).toLocaleString()}
          </p>
          {subtext && (
            <p className="text-sm text-gray-500 mt-1">{subtext}</p>
          )}
        </div>
        <div className={`p-3 rounded-xl ${colorClasses[color]}`}>{icon}</div>
      </div>
    </div>
  )
}
